version: "3"

volumes: 
  mysql-data:

services: 
  watchtower:
    image: v2tec/watchtower
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    command: --label-enable
  app:
    image: containerize/cms:latest
    restart: always
    labels: 
      - com.centurylinklabs.watchtower.enable=true
    extra_hosts: 
      - mysql:192.168.20.25
    environment: 
      - PORT=8000
      - MYSQL_DATABASE=root:root@tcp(mysql:3306)/sme?charset=utf8mb4&parseTime=true
    ports:
      - "8000:8000"
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sme
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "13306:3306"
  ui:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment: 
      - PMA_HOST=mysql
    ports:
      - "8085:80"